# Generated by Django 4.1.7 on 2023-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
