# Generated by Django 4.1.7 on 2023-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_product_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GF', 'GF'), ('V', 'V'), ('VG', 'VG')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Pizza', 'Pizza'), ('Sides', 'Sides'), ('Dessert', 'Dessert'), ('Local goods', 'Local goods')], max_length=200, null=True),
        ),
    ]
