# Generated by Django 4.1.7 on 2023-03-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_product_category_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GF', 'GF'), ('V', 'V'), ('VG', 'VG'), ('No', 'No')], max_length=200, null=True),
        ),
    ]
