# Generated by Django 4.1.7 on 2023-03-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_product_source_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source',
        ),
    ]
