# Generated by Django 4.1.7 on 2023-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idnum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.FloatField(null=True),
        ),
    ]
