# Generated by Django 4.1.7 on 2023-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_product_available_remove_product_outofdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In date', 'In date'), ('Out of date', 'Out of date'), ('Available', 'Available'), ('unavailable', 'Unavailable')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
