# Generated by Django 4.1.7 on 2023-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_product_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In date', 'In date'), ('Out of date', 'Out of date'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=200, null=True),
        ),
    ]
