# Generated by Django 4.1.7 on 2023-05-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mistake',
            field=models.CharField(choices=[('Mistake', 'Mistake'), ('No mistake', 'No mistake')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
