# Generated by Django 4.1.7 on 2023-05-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_product_mistake_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mistake',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake', models.CharField(choices=[('Mistake', 'Mistake'), ('No mistake', 'No mistake')], max_length=200, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
        ),
    ]
