# Generated by Django 4.1.7 on 2023-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_product_mistake_product_quantity_delete_mistake'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake', models.CharField(choices=[('Mistake', 'Mistake'), ('No mistake', 'No mistake')], max_length=200, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('In date', 'In date'), ('Out of date', 'Out of date'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('GF', 'GF'), ('V', 'V'), ('VG', 'VG'), ('No', 'No')], max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
                ('allergens', models.CharField(max_length=200, null=True)),
                ('idnum', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Pizza', 'Pizza'), ('Sides', 'Sides'), ('Dessert', 'Dessert')], max_length=200, null=True),
        ),
    ]
