# Generated by Django 4.1.7 on 2023-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_localgoods_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mistakeprice',
            field=models.FloatField(null=True),
        ),
    ]
